version: "3.8"

services:
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app_network

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    container_name: db
    hostname: mongo
    image: mongo:latest
    volumes:
      - slack_db:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  slack_db:
